# Generated by Django 4.2.17 on 2025-01-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oveja',
            name='fecha_muerte',
            field=models.DateTimeField(),
        ),
    ]
