# Generated by Django 4.2.17 on 2025-01-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0002_alter_oveja_fecha_muerte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oveja',
            name='fecha_muerte',
            field=models.DateField(blank=True, null=True),
        ),
    ]
