# Generated by Django 4.2.17 on 2024-12-30 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0002_alter_user_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oveja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('BU', models.CharField(max_length=50, unique=True)),
                ('RP', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
                ('edad', models.PositiveIntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('calificador_pureza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ganaderia.calificadorpureza')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ovejas', to=settings.AUTH_USER_MODEL)),
                ('oveja_madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_madre', to='ganaderia.oveja')),
                ('oveja_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_padre', to='ganaderia.oveja')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.raza')),
            ],
        ),
    ]
