# Generated by Django 4.2.17 on 2024-12-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0003_oveja'),
    ]

    operations = [
        migrations.AddField(
            model_name='oveja',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('vendida', 'Vendida'), ('muerta', 'Muerta')], default='activa', max_length=10),
        ),
    ]
