# Generated by Django 4.2.17 on 2024-12-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0004_oveja_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oveja',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
