# Generated by Django 4.2.17 on 2025-01-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0005_alter_oveja_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='oveja',
            name='rp_madre_externo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oveja',
            name='rp_padre_externo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
