# Generated by Django 4.2.17 on 2025-01-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0006_oveja_rp_madre_externo_oveja_rp_padre_externo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('valor_carne', models.FloatField(blank=True, null=True)),
                ('valor', models.FloatField(default=0.0)),
                ('tipo_venta', models.CharField(choices=[('remate', 'Remate'), ('individual', 'Individual'), ('frigorifico', 'Frigorífico'), ('donacion', 'Donación')], max_length=20)),
                ('ovejas', models.ManyToManyField(blank=True, related_name='ventas', to='ganaderia.oveja')),
            ],
        ),
    ]
