# Generated by Django 4.2.17 on 2025-01-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0008_venta_establecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='peso_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
