# Generated by Django 4.2.17 on 2025-01-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0009_venta_peso_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registro_ARU_criador',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
