# Generated by Django 4.2.17 on 2025-01-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0010_user_registro_aru_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oveja',
            name='nombre',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
